; This file is for the FamiStudio Sound Engine and was generated by FamiStudio
; File: Vaadivasal_Sounds.s
; Required flags for Vaadivasal_Music:
; FAMISTUDIO_USE_FAMITRACKER_TEMPO = 1

.export _music_data_vaadivasal_music:=music_data_vaadivasal_music

music_data_vaadivasal_music:
	.byte 8
	.word @instruments
	.word @samples-4
; 00 : Tamil_Thappa_1
	.word @song0ch0
	.word @song0ch1
	.word @song0ch2
	.word @song0ch3
	.word @song0ch4
	.word 307,256
; 01 : Game_Start
	.word @song1ch0
	.word @song1ch1
	.word @song1ch2
	.word @song1ch3
	.word @song1ch4
	.word 307,256
; 02 : Game_Win
	.word @song2ch0
	.word @song2ch1
	.word @song2ch2
	.word @song2ch3
	.word @song2ch4
	.word 307,256
; 03 : Game_Over
	.word @song3ch0
	.word @song3ch1
	.word @song3ch2
	.word @song3ch3
	.word @song3ch4
	.word 307,256
; 04 : QTE_Success
	.word @song4ch0
	.word @song4ch1
	.word @song4ch2
	.word @song4ch3
	.word @song4ch4
	.word 307,256
; 05 : QTE_Failure
	.word @song5ch0
	.word @song5ch1
	.word @song5ch2
	.word @song5ch3
	.word @song5ch4
	.word 307,256
; 06 : Bull_hit_player
	.word @song6ch0
	.word @song6ch1
	.word @song6ch2
	.word @song6ch3
	.word @song6ch4
	.word 307,256
; 07 : Player_catch_bull
	.word @song7ch0
	.word @song7ch1
	.word @song7ch2
	.word @song7ch3
	.word @song7ch4
	.word 307,256

.export music_data_vaadivasal_music
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env1,@env2,@env3,@env0 ; 00 : Instrument 1

@env0:
	.byte $00,$c0,$7f,$00,$02
@env1:
	.byte $00,$cf,$c8,$c3,$c1,$00,$04
@env2:
	.byte $c0,$7f,$00,$01
@env3:
	.byte $7f,$00,$00

@samples:

@song0ch0:
	.byte $46, $01, $80
@song0ref4:
	.byte $29, $89, $2c, $89, $2e, $89, $00, $b9
	.byte $41, $08
	.word @song0ref4
@song0ch0loop:
@song0ref16:
	.byte $29, $89, $00, $89, $2c, $89, $00, $89, $2e, $89, $00, $89, $2c, $89, $00, $89, $29
@song0ref33:
	.byte $89, $00, $89, $27, $89, $00, $89, $25, $89, $00, $89, $29, $89, $00, $89
	.byte $41, $10
	.word @song0ref16
	.byte $2c
	.byte $41, $0f
	.word @song0ref33
	.byte $41, $1e
	.word @song0ref16
	.byte $29, $89, $42
	.word @song0ch0loop
@song0ch1:
	.byte $ff, $bf
@song0ch1loop:
	.byte $af, $80, $20, $89, $00, $89, $22, $89, $00, $b9, $20, $89, $00, $89, $1d, $89, $00, $89, $97
@song0ref85:
	.byte $20, $89, $00, $89, $20, $89, $00, $89, $22, $89, $00, $a1
	.byte $41, $08
	.word @song0ref85
	.byte $1d, $89, $00, $89, $ff, $a7, $1d, $89, $00, $89, $42
	.word @song0ch1loop
@song0ch2:
	.byte $80, $0d, $dd, $0d, $dd
@song0ch2loop:
	.byte $0d, $dd, $08, $dd, $0d, $ad, $0b, $ad, $0a, $ad, $08, $ad, $08, $ad, $0a, $ad, $0b, $ad, $0d, $ad, $42
	.word @song0ch2loop
@song0ch3:
	.byte $80
@song0ref143:
	.byte $25, $89, $00, $a1, $25, $89, $00, $a1
	.byte $41, $08
	.word @song0ref143
@song0ch3loop:
@song0ref155:
	.byte $25, $89, $00, $a1, $25, $89, $00, $95, $25, $89, $25, $89, $00, $a1
@song0ref169:
	.byte $25, $89, $00, $89, $25, $89, $00, $89
	.byte $41, $08
	.word @song0ref169
	.byte $25, $89, $00, $89, $25, $89, $25, $89
	.byte $41, $08
	.word @song0ref169
	.byte $41, $08
	.word @song0ref169
	.byte $41, $16
	.word @song0ref155
	.byte $42
	.word @song0ch3loop
@song0ch4:
	.byte $ff, $bf
@song0ch4loop:
	.byte $ff, $bf, $ff, $bf, $ff, $bf, $42
	.word @song0ch4loop
@song1ch0:
	.byte $46, $0a, $80, $25, $81, $27, $81, $29, $81, $00, $81, $2c, $85, $00, $85
@song1ch0loop:
	.byte $9f, $42
	.word @song1ch0loop
@song1ch1:
	.byte $89, $80, $1d, $81, $00, $81, $20, $81, $00, $87
@song1ch1loop:
	.byte $9f, $42
	.word @song1ch1loop
@song1ch2:
	.byte $80, $0d, $8d, $00, $8d
@song1ch2loop:
	.byte $9f, $42
	.word @song1ch2loop
@song1ch3:
	.byte $80, $25, $00, $83, $25, $00, $81, $25, $25, $00, $83, $25, $00, $25, $00
@song1ch3loop:
	.byte $9f, $42
	.word @song1ch3loop
@song1ch4:
	.byte $9f
@song1ch4loop:
	.byte $9f, $42
	.word @song1ch4loop
@song2ch0:
	.byte $46, $0a, $80, $25, $81, $27, $81, $29, $81, $2c, $81, $2e, $85, $00, $85, $2e, $89, $31, $89, $00, $85
@song2ch0loop:
	.byte $9f, $42
	.word @song2ch0loop
@song2ch1:
	.byte $89, $80, $1d, $00, $83, $20, $00, $81, $1d, $81, $20, $81, $1d, $81, $00, $81, $20, $81, $00, $91
@song2ch1loop:
	.byte $9f, $42
	.word @song2ch1loop
@song2ch2:
	.byte $80, $0d, $85, $00, $85, $14, $85, $00, $85, $0d, $89, $14, $89, $00, $85
@song2ch2loop:
	.byte $9f, $42
	.word @song2ch2loop
@song2ch3:
	.byte $9b, $80, $24, $81, $00, $9d
@song2ch3loop:
	.byte $9f, $42
	.word @song2ch3loop
@song2ch4:
	.byte $9f, $9f
@song2ch4loop:
	.byte $9f, $42
	.word @song2ch4loop
@song3ch0:
	.byte $46, $0a, $80, $2e, $85, $2c, $85, $29, $85, $27, $85, $25, $89, $00, $91
@song3ch0loop:
	.byte $9f, $42
	.word @song3ch0loop
@song3ch1:
	.byte $89, $80, $1d, $00, $8b, $1b, $00, $81, $9f
@song3ch1loop:
	.byte $9f, $42
	.word @song3ch1loop
@song3ch2:
	.byte $80, $16, $8d, $11, $8d, $0d, $89, $00, $91
@song3ch2loop:
	.byte $9f, $42
	.word @song3ch2loop
@song3ch4:
@song3ch3:
	.byte $9f, $9f
@song3ch3loop:
	.byte $9f, $42
	.word @song3ch3loop
@song4ch0:
	.byte $46, $0a, $80, $29, $81, $2e, $81, $00, $95
@song4ch0loop:
	.byte $9f, $42
	.word @song4ch0loop
@song4ch4:
@song4ch1:
	.byte $9f
@song4ch1loop:
	.byte $9f, $42
	.word @song4ch1loop
@song4ch2:
	.byte $80, $0d, $85, $00, $95
@song4ch2loop:
	.byte $9f, $42
	.word @song4ch2loop
@song4ch3:
	.byte $80, $25, $85, $00, $95
@song4ch3loop:
	.byte $9f, $42
	.word @song4ch3loop
@song5ch0:
	.byte $46, $0a, $80, $2c, $81, $27, $81, $00, $95
@song5ch0loop:
	.byte $9f, $42
	.word @song5ch0loop
@song5ch4:
@song5ch1:
	.byte $9f
@song5ch1loop:
	.byte $9f, $42
	.word @song5ch1loop
@song5ch2:
	.byte $80, $14, $85, $00, $95
@song5ch2loop:
	.byte $9f, $42
	.word @song5ch2loop
@song5ch3:
	.byte $80, $25, $85, $00, $95
@song5ch3loop:
	.byte $9f, $42
	.word @song5ch3loop
@song6ch0:
	.byte $46, $0a, $80, $0d, $81, $00, $81
@song6ch0loop:
	.byte $87, $42
	.word @song6ch0loop
@song6ch4:
@song6ch2:
@song6ch1:
	.byte $87
@song6ch1loop:
	.byte $87, $42
	.word @song6ch1loop
@song6ch3:
	.byte $80, $25, $83, $00
@song6ch3loop:
	.byte $87, $42
	.word @song6ch3loop
@song7ch0:
	.byte $46, $0a, $81, $80, $25, $00, $25, $00, $95
@song7ch0loop:
	.byte $9f, $42
	.word @song7ch0loop
@song7ch1:
	.byte $80, $25, $00, $25, $00, $97
@song7ch1loop:
	.byte $9f, $42
	.word @song7ch1loop
@song7ch2:
	.byte $81, $80, $0d, $00, $0d, $00, $95
@song7ch2loop:
	.byte $9f, $42
	.word @song7ch2loop
@song7ch3:
	.byte $80, $25, $85, $00, $95
@song7ch3loop:
	.byte $9f, $42
	.word @song7ch3loop
@song7ch4:
	.byte $9f
@song7ch4loop:
	.byte $9f, $42
	.word @song7ch4loop